name: Github Releases To Discord
description: Send automatic styled releases to Discord.
inputs:
  webhook_url:
    description: Discord's webhook url. Use GH repo secrets.
    required: true
runs:
  using: 'node16'
  main: 'index.js'