on:
  release:
    types: [published]
name: github-release-to-discord
jobs:
  github-release-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-release-to-discord@v1.12.0
        id: release
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}