on:
  release:
    types: [published]

jobs:
  github-release-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Handle Release
        uses: ./ # Uses an action in the root directory
        id: release
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}